### ISSUE TITLE
Investigate why the deallocation of VMs is taking too long.

### ISSUE THREAD

**Issue by giovannifs** [giovannifs/cloudsim#2]
As per title.

**Comment by alessandroliafook** [comment]
Through the Jprofiller that was discovered that the VMscheduler was clearing and repopulates the map, that stores all vms allocated on the host, every time that was deallocated a VM to the host. 
Therefore, we developed a new scheduler, based solely on the allocated mips value and available, where the vm to be destroyed is removed from the map without the need to empty it. 
Thus, it was possible to expedite the process of deallocation of the vm for a host, so that this process has the agility expected.

**Comment by giovannifs** [comment]
We code was using some data structures that were not the most appropriate for that. We refactored the code.
